user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

